---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    type: appserver
spec:
  containers:
    - name: mytomcat
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 8080
      resources:
        limits:
          cpu: "128m"
          memory: "500Mi"
        requests:
          cpu: "64m"
          memory: "250Mi"
